version: '3'

services:
  frontend:
    image: angular-dev
    container_name: frontend
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - my-network

  backend:
    image: my-backend
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./backend:/app/backend
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

database:
    build:
      context: ./database
    ports:
      - "3306:3306"   # Puerto de MySQL
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: caferosita
      MYSQL_USER: root
      MYSQL_PASSWORD: null
    networks:
      - app-network